
---CREATION DES VUES 

--selection des stagiairs actifs 
SET SEARCH_PATH="RH"
CREATE VIEW "VW_STAGIAIRE_ACTIF" AS 
SELECT * FROM "TB_STAGIAIRES" WHERE "BL_ACTIF";

--selection des stagiairs non actifs 
CREATE VIEW "VW_STAGIAIRE_NON_ACTIF" AS 
SELECT * FROM "TB_STAGIAIRES" WHERE NOT "BL_ACTIF";
