--------------------------------------------------------------
-----CREATION DES TABLES NECESSAIRE-------------------
------------------------------------------------------

----initialisation du shema a utiliser 
SET SEARCH_PATH="RH";

---------table 1: TB_STAGIAIRES  

---DROP TYPE IF EXIST "CIVILITE"

CREATE TYPE "CIVILITE" AS ENUM('Mlle','Mme','Mr');
---script de creation de la table :

---DROP TABLE IF EXIST"TB_STAGIAIRES" CASCADE ;
CREATE TABLE "TB_STAGIAIRES"
(
"ID_STAGIAIRE"        VARCHAR(10) NOT NULL,
"LB_CIVILITE"          "CIVILITE" NOT NULL,
"LB_NOM_STAGIAIRE"     VARCHAR(100) NOT NULL,
"LB_PREN_STAGIAIRE"    VARCHAR(100) NOT NULL,
"DT_NAISSANCE"         DATE NOT NULL,
"LB_LIEU_NAISSANCE"    VARCHAR(100) NOT NULL,
"LB_NATIONALITE"       VARCHAR(100) NOT NULL,
"CD_POSTAL"            VARCHAR(100) NOT NULL,
"LB_VILLE"             VARCHAR(100) NOT NULL,
"LB_PAYS"              VARCHAR(100) NOT NULL,
"LB_ADRESSE"           VARCHAR(100) NOT NULL,
"LB_DIPLOME_ELEVE"     VARCHAR(100) NOT NULL,
"NUM_TEL"              VARCHAR(100) NOT NULL,
"LB_SITUATION_MAT"     VARCHAR(100) NOT NULL,
"NUM_NIR"              VARCHAR(20) NOT NULL,
"BL_ACTIF"             BOOLEAN NOT NULL,
"BL_EMBAUCHER"         BOOLEAN NOT NULL,
CONSTRAINT "TB_SATGIAIRE_PKEY" PRIMARY KEY("ID_STAGIAIRE"));

-----------------------------------------------------------------
-------table 2 TB_TYPE CONTRATS 
CREATE TABLE "TB_TYPE_CONTRAT"
(

"CD_TYPE_CONTRAT"  VARCHAR(10) NOT NULL,
"LB_TYPE_CONTRAT"    VARCHAR(100) NOT NULL,
UNIQUE ("LB_TYPE_CONTRAT"),
CONSTRAINT "TB_TYPE_CONTRAT_PKEY" PRIMARY KEY("CD_TYPE_CONTRAT")
);



-------------------------------------------------------
---------table 3 : table des equipes 

CREATE TABLE "TB_EQUIPE"
(
"CD_EQUIPE"               VARCHAR(100) NOT NULL,
"LB_NOM_EQUIPE"           VARCHAR(100) NOT NULL,
"LB_RESPONSABLE_EQUIPE"   VARCHAR(100) NOT NULL,
UNIQUE ("LB_NOM_EQUIPE"),
CONSTRAINT "TB_EQUIPE_PKEY" PRIMARY KEY("CD_EQUIPE"));



------------------------------------------------------
----------table4 constrat 

CREATE TABLE "TB_CONTART" (
    "ID_CONTRAT"          VARCHAR(10) NOT NULL,
    "DT_DEBUT"            DATE NOT NULL,
    "DT_FIN"              DATE NOT NULL,
    "CD_TYPE_CONTRAT"     VARCHAR(10) NOT NULL,
    "ID_STAGIAIRE"        VARCHAR(10) NOT NULL,
    "NB_SALAIR"           NUMERIC NOT NULL,
    "DT_ARRET_CONTRAT"    DATE,
    "LB_MOTIF_ARRET"      VARCHAR(50),

    CONSTRAINT "TB_CONTART_PKEY" PRIMARY KEY ("ID_CONTRAT"),

    CONSTRAINT "CD_TYPE_CONTRAT_FKEY"
        FOREIGN KEY ("CD_TYPE_CONTRAT")
        REFERENCES "TB_TYPE_CONTRAT"("CD_TYPE_CONTRAT"),

    CONSTRAINT "TB_CONTRAT_STAGIAIRE_FKEY"
        FOREIGN KEY ("ID_STAGIAIRE")
        REFERENCES "TB_STAGIAIRES"("ID_STAGIAIRE")
);


------------------table 5 AFFECTATION EQUIPE 

CREATE TABLE "TB_AFFECTATION_EQUIPE"(
"ID_STAGIAIRE"   VARCHAR(10) NOT NULL,
"CD_EQUIPE"   	 VARCHAR(10) NOT NULL,
"DT_DEBUT"       DATE NOT NULL,
"DT_FIN"         DATE,
"LB_INFO_PROJET_ACTUEL"   VARCHAR(100) NOT NULL,
 CONSTRAINT "TB_AFFECTATION_EQUIPE_PKEY" PRIMARY KEY ("ID_STAGIAIRE"),

    CONSTRAINT "TB_AFFECTATION_EQUIPE"
        FOREIGN KEY ("ID_STAGIAIRE")
        REFERENCES "TB_STAGIAIRES"("ID_STAGIAIRE"),

    CONSTRAINT "TB_AFFECTATION_EQUIPE_FKEY"
        FOREIGN KEY ("CD_EQUIPE")
        REFERENCES "TB_EQUIPE"("CD_EQUIPE")
);